INSERT INTO xcart_languages SET code='en', name='eml_amazon_pa_pm2be_updated', value='There was a problem with the payment method chosen. You need to update your payment method on <a href="{{url2update_pm}}" target="_blank">this page</a>.<br /><br />Alternatively, you can visit the <a href="https://pay.amazon.com/uk/" target="_blank">Amazon Pay website</a>, look up your order, and update the payment method by following the instructions on the webpage.', topic='E-Mail';
INSERT INTO xcart_languages SET code='en', name='eml_amazon_pa_pm2be_updated_subj', value='Amazon Pay payment method needs to be updated for the order #{{orderid}}', topic='E-Mail';
INSERT INTO xcart_languages SET code='en', name='lbl_amazon_pa_amazon_advanced', value='Amazon Pay', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_amazon_pa_asynchronous', value='Asynchronous', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_amazon_pa_auth_then_capture', value='Authorization then capture', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_amazon_pa_capture_now', value='Immediate Charge', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_amazon_pa_capture_status', value='Capture status', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_amazon_pa_checkout', value='Amazon Checkout', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_amazon_pa_confirm_capture', value='This operation will capture funds from customer. Please confirm to proceed.', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_amazon_pa_confirm_refund', value='This operation will refund funds to customer. Please confirm to proceed.', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_amazon_pa_confirm_void', value='This operation will cancel order. Payment authorization will be voided. Please confirm to proceed.', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_amazon_pa_order_avail_actions', value='Amazon Pay available order actions', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_amazon_pa_refresh', value='Refresh Status', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_amazon_pa_refund_status', value='Refund status', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_amazon_pa_synchronous', value='Synchronous', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_payment_capture_pending', value='Payment capture is pending', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_payment_refund_pending', value='Payment refund is pending', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='module_descr_Amazon_Payments_Advanced', value='This module enables Amazon Pay functionality', topic='Modules';
INSERT INTO xcart_languages SET code='en', name='module_name_Amazon_Payments_Advanced', value='Amazon Pay', topic='Labels';
INSERT INTO xcart_languages VALUES ('en','module_requirements_Amazon_Payments_Advanced', 'The module requires secure connection via HTTPS (http://help.x-cart.com/index.php?title=X-Cart:Configuring_HTTPS).<br> The OpenSSL extension and hash (http://www.php.net/manual/en/function.hash.php) functions should be also available.<br />', 'Modules');
INSERT INTO xcart_languages VALUES ('en','opt_amazon_pa_access_key','Access Key ID','Options');
INSERT INTO xcart_languages VALUES ('en','opt_amazon_pa_capture_mode','Capture mode','Options');
INSERT INTO xcart_languages VALUES ('en','opt_amazon_pa_cid','Client ID','Options');
INSERT INTO xcart_languages VALUES ('en','opt_amazon_pa_currency','Currency','Options');
INSERT INTO xcart_languages VALUES ('en','opt_amazon_pa_mode','Operation mode','Options');
INSERT INTO xcart_languages VALUES ('en','opt_amazon_pa_region','Region','Options');
INSERT INTO xcart_languages VALUES ('en','opt_amazon_pa_secret_key','Secret Access Key','Options');
INSERT INTO xcart_languages VALUES ('en','opt_amazon_pa_sid','Amazon Seller ID','Options');
INSERT INTO xcart_languages VALUES ('en','opt_amazon_pa_sync_mode','Type of authorization request','Options');
INSERT INTO xcart_languages VALUES ('en','txt_amazon_pa_configuration_info','<p>Please make sure the following settings are configured properly in your:</p><p><em>&nbsp; </em><a href="https://sellercentral.amazon.com/" target="_blank">Amazon Payments account</a>:</p><p><strong>&nbsp; &nbsp; Merchant URL</strong>&nbsp;field on the <a href="https://sellercentral.amazon.com/gp/pyop/seller/account/settings/user-settings-edit.html" target="_blank">Integration Settings</a> page: <em>{{merchant_url}}</em></p><p><em>&nbsp;&nbsp;</em><a href="https://sellercentral.amazon.com/" target="_blank">Login with Amazon account</a>:</p><p>&nbsp; &nbsp;&nbsp;<strong>Allowed JavaScript Origins</strong>&nbsp;option&nbsp;on the <a href="https://sellercentral.amazon.com/gp/homepage.html" target="_blank">Application settings</a> page:&nbsp;<em>{{allowed_javascript_origins}}</em></p><p><em>&nbsp; &nbsp;&nbsp;</em><strong>Allowed Return URLs</strong>&nbsp;option&nbsp;on the <a href="https://sellercentral.amazon.com/gp/homepage.html" target="_blank">Application settings</a> page:&nbsp;<em>{{allowed_return_urls}}</em></p>','Text');
