REPLACE INTO xcart_languages SET code='en', name='err_facebook_ecomm_dir_permission_denied', value='Cannot write the file to {{path}} directory: please make sure the directory has write permissions', topic='Errors';
REPLACE INTO xcart_languages SET code='en', name='err_facebook_ecomm_no_catalog', value='No products have been selected. Please choose to <a href=\"search.php\" class=\"message-e\" target=\"_blank\">edit products</a> and select the \'Add to Facebook product feed\' option for all the products that need to be included into Facebook feeds.', topic='Errors';
REPLACE INTO xcart_languages SET code='en', name='lbl_facebook_ecomm_add_to_feed', value='Add to Facebook product feeds', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_facebook_ecomm_age_group', value='Age group (May be overwritten by the "age_group" extra field)', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_facebook_ecomm_currency', value='Currency (will be used in the customer area)', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_facebook_ecomm_daily', value='daily', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_facebook_ecomm_feeds', value='Feeds', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_facebook_ecomm_fetch_date', value='Fetch date', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_facebook_ecomm_hourly', value='hourly', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_facebook_ecomm_last_feeds', value='Last feeds', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_facebook_ecomm_no_feeds', value='No feeds', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_facebook_ecomm_update_date', value='Update date', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_facebook_ecomm_weekly', value='weekly', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_facebook_ecomm_generate_feed', value='Generate a new feed', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='module_descr_Facebook_Ecommerce', value='This add-on syncs your X-Cart and your Facebook catalogs to help you make maximum use of Facebook Marketing tools having your products promoted to the right audience in the right place at the right time.', topic='Modules';
REPLACE INTO xcart_languages SET code='en', name='module_name_Facebook_Ecommerce', value='Facebook E-Commerce', topic='Modules';
REPLACE INTO xcart_languages SET code='en', name='opt_facebook_ecomm_frequency_feed', value='Frequency of product feeds renewal', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_descr_facebook_ecomm_frequency_feed', value='Periodic execution by cron should be set according to <a href="https://help.x-cart.com/index.php?title=X-Cart:Cron.php_-_Script_for_Periodic_Tasks" target="_blank">the guidelines</a><br />The recommended mode is from the command line (for example, via crontab).<br />The recommended frequency is no more than once per hour.', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_facebook_ecomm_general_settings', value='General settings', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_facebook_ecomm_pixel_id', value='Facebook Pixel ID', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_facebook_ecomm_weight_unit', value='Weight symbol', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='txt_facebook_ecomm_feed_format_help', value='To add any of the fields listed at <a href="https://developers.facebook.com/docs/marketing-api/dynamic-product-ads/product-catalog/v2.9#required-fields" target="_blank">https://developers.facebook.com/docs/marketing-api/dynamic-product-ads/product-catalog/v2.9#required-fields</a><br/>follow the steps below:<br/><br/>&nbsp;1) Add the field (or make sure it already exists) in modules/Facebook_Ecommerce/config.php after the following line:<br/>$export_product_extrafields_headers_g["Facebook_Ecommerce"] = array(<br/><br/>&nbsp;2)Add an extra field with the same service name.<br/><br />&nbsp;3)Add a value for this extra field in the product details.', topic='Text';
