REPLACE INTO xcart_languages SET code='en', name='module_descr_Segment', value='Segment is a powerful data aggregator, it tracks e-commerce events and sends this info to such apps as Mixpanel, Google Analytics, Localytics, RJ Metrics, SalesForce, HubSpot, Optimizely, Clicky and other data processing tools.<br /><b>Note:</b> This module requires Google Analytics module to be disabled.', topic='Modules';
REPLACE INTO xcart_languages SET code='en', name='module_name_Segment', value='Segment', topic='Modules';
REPLACE INTO xcart_languages SET code='en', name='msg_adm_segment_ga_both_modules_are_enabled', value='Your store has the modules \'Google Analytics\' and \'Segment\' enabled at the same time. Simultaneous use of these two modules may <a href=\"https://segment.com/docs/integrations/google-analytics/#getting-started\" target=\"_blank\">cause errors</a>. It is recommended to disable one of the modules to ensure there is no conflict.', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_sep_cart_events', value='Cart events', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_sep_catalog_events', value='Catalog events', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_sep_connection', value='Connection settings', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_sep_order_events', value='Order events', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_sep_produc_events', value='Product events', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_sep_user_events', value='User events', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_added_product', value='Track the event "Added Product"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_completed_order', value='Track the event "Completed Order"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_logged_in', value='Track the event "Logged In"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_logged_off', value='Track the event "Logged Off"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_open_login_popup', value='Track the event "Open Login Popup"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_open_minicart', value='Track the event "Open Minicart"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_product_dpimages', value='Track the event "Detailed images jump"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_product_feedback', value='Track the event "Customer feedback jump"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_product_recommends', value='Track the event "Customers also bought jump"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_product_relateds', value='Track the event "Related products jump"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_product_send2friend', value='Track the event "Send to friend jump"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_product_special_offers', value='Track the event "Special offers jump"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_product_xmagnifier', value='Track the event "Magnifier More views jump"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_removed_product', value='Track the event "Removed Product"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_search_products', value='Track the event "Search Products"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_send2friend', value='Track the event "Send to Friend"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_sent_contact_us', value='Track the event "Sent Contact Us"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_sent_survey', value='Track the event "Sent Survey"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_updated_product', value='Track the event "Updated Product Quantity"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_viewed_category', value='Track the event "Viewed Product Category"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_t_viewed_product', value='Track the event "Viewed Product"', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_segment_write_key', value='Write key (You can find it in your project setup guide or settings)', topic='Options';

