REPLACE INTO xcart_languages SET code='en', name='err_shippingeasy_order_export', value='Order has NOT been exported. Check \"ShippingEasy\" logs for details.', topic='Errors';
REPLACE INTO xcart_languages SET code='en', name='err_shippingeasy_orders_export', value='Some orders have NOT been exported. Check \"ShippingEasy\" logs for details.', topic='Errors';
REPLACE INTO xcart_languages SET code='en', name='lbl_shippingeasy_awaiting_fulfillment', value='Awaiting fulfillment', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_shippingeasy_awaiting_payment', value='Awaiting payment', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_shippingeasy_awaiting_shipment', value='Awaiting shipment', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_shippingeasy_export_to', value='Export to ShippingEasy', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_shippingeasy_partially_shipped', value='Partially shipped', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_shippingeasy_shipped', value='Shipped', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_shippingeasy_status', value='ShippingEasy status', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_shippingeasy_statuses', value='ShippingEasy statuses', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_shippingeasy_x_status', value='X-Cart status', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='module_name_ShippingEasy', value='ShippingEasy', topic='Modules';
REPLACE INTO xcart_languages SET code='en', name='module_descr_ShippingEasy', value='Save time and money with the shipping solution built for eCommerce retailers! ShippingEasy downloads orders in real-time and automates your shipping based on carrier, service, package and more.', topic='Modules';
REPLACE INTO xcart_languages SET code='en', name='msg_shippingeasy_item_added', value='Item has been added successfully', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='msg_shippingeasy_item_deleted', value='Items have been deleted successfully', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='opt_log_shippingeasy', value='ShippingEasy', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_shippingeasy_api_key', value='API Key', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_shippingeasy_api_secret', value='API Secret', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_shippingeasy_staging_account', value='Staging account', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_shippingeasy_store_api_key', value='Store API Key', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='txt_shippingeasy_account_note', value='View details and get API credentials <a href=\"http://shippingeasy.com/integrate-your-shipping-for-xcart-with-the-shippingeasy-app/?se-ref=96\" target=\"_blank\">here</a>', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='txt_shippingeasy_no_data', value='No data', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='txt_shippingeasy_order_already_exported', value='Order is already exported', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='txt_shippingeasy_order_export', value='Order has been successfully exported', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='txt_shippingeasy_orders_already_exported', value='All orders are already exported', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='txt_shippingeasy_orders_export', value='Orders have been successfully exported', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='txt_shippingeasy_statuses_top_text', value='In this section you can define correspondence between X-Cart and ShippingEasy order statuses', topic='Text';
